```puml
@startuml
autonumber
hide footbox

skinparam legendBackgroundColor #FFFFFF
skinparam legendBorderColor #FFFFFF
legend top right
    <#FFFFFF,#FFFFFF>|<#lightgreen>     | Service Specific Area|
    |<#e6e6fa>      | Common Logic |
end legend

actor user #white
database auth_codes #lightgreen
database auth_target as "subject" #lightgreen
participant admin_system #lightgreen
actor admin #white


admin -> admin_system: issue credential offer
admin_system -> admin_system: issue code as pre_auth
admin_system -> auth_codes: save code
note over auth_target
 set needs_proof to true
 if the credential needs proof of possession
end note
admin_system -> auth_target: bind auth code
admin_system -> admin_system: issue user_pin if need
admin_system --> admin: credential offer
admin -> user: credential offer, user_pin

@enduml
```
